service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: 0.0.0.0:13133

  jaeger_query:
    storage:
      traces: primary_store
      traces_archive: archive_store

  jaeger_storage:
    backends:
      primary_store:
        memory:
          max_traces: 100000
      archive_store:
        memory:
          max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:
  zipkin:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: primary_store
