{{ if .Values.userconfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configmap
  namespace: {{ include "jaeger.namespace" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
data:
  config.yaml: |
        {{- .Values.userconfig | nindent 4 }}
{{- end }}