{{- if .Values.allInOne.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configmap
  namespace: {{ include "jaeger.namespace" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
data:
  config.yaml: |
        service:
          extensions: {{ include "jaeger.serviceExtensions" . }}
          pipelines:
            traces:
              receivers: {{ include "jaeger.serviceReceivers" . }}
              processors: {{ include "jaeger.serviceProcessors" . }}
              exporters: {{ include "jaeger.serviceExporters" . }}

        extensions:
          {{- include "jaeger.extensionsConfig" . | nindent 6 }}
        receivers:
          {{- include "jaeger.receiversConfig" . | nindent 6 }}
        processors:
          {{- include "jaeger.processorsConfig" . | nindent 6 }}
        exporters:
          {{- include "jaeger.exportersConfig" . | nindent 6 }}
{{- end }}