{{ if (and (not .Values.userconfig) .Values.provisionDataStore.elasticsearch) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: {{ include "jaeger.namespace" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
data:
  user-config.yaml: |
    service:
      extensions: [jaeger_storage, jaeger_query, healthcheckv2]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_storage_exporter]

    extensions:
      healthcheckv2:
        use_v2: true
        http:
            endpoint: 0.0.0.0:13133

      jaeger_query:
        storage:
          traces: some_storage
          traces_archive: another_storage


      jaeger_storage:
        backends:
          some_storage:
            elasticsearch:
              index_prefix: {{- .Values.config.extensions.jaeger_storage.backends.elasticsearch.index_prefix | quote | indent 2 }}
              server_urls: ["{{ include "elasticsearch.client.url" . }}"]
              username: {{- .Values.storage.elasticsearch.user | quote | indent 2 }}
              {{- if .Values.storage.elasticsearch.password }}
              password: {{- .Values.storage.elasticsearch.password | quote | indent 2 }}
              {{- end }}
          another_storage:
            elasticsearch:
              index_prefix: {{- .Values.config.extensions.jaeger_storage.backends.elasticsearch.index_prefix_archive | quote | indent 2 }}
              server_urls: ["{{ include "elasticsearch.client.url" . }}"]
              username: {{- .Values.config.extensions.jaeger_storage.backends.elasticsearch.user | quote | indent 2 }}
              {{- if .Values.config.extensions.jaeger_storage.backends.elasticsearch.password }}
              password: {{- .Values.config.extensions.jaeger_storage.backends.elasticsearch.password | quote | indent 2 }}
              {{- end }}

    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      jaeger_storage_exporter:
        trace_storage: some_storage
{{- end }}
