# this is a user-provided config file that will be mounted into the all-in-one deployments
{{ if .Values.userconfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: {{ include "jaeger.namespace" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
data:
  user-config.yaml: |
    {{- .Values.userconfig | nindent 4 }}
{{- end }}