apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: default
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation  # Optional: Deletes the hook before the next installation
data:
  config.yaml: |
    service:
      extensions: {{ toYaml .Values.service.extensions | indent 6 }}
      pipelines:
        traces:
          receivers: {{ toYaml .Values.service.pipelines.traces.receivers | indent 10 }}
          processors: {{ toYaml .Values.service.pipelines.traces.processors | indent 10 }}
          exporters: {{ toYaml .Values.service.pipelines.traces.exporters | indent 10 }}

    extensions:
      healthcheckv2: {{ toYaml .Values.extensions.healthcheckv2 | indent 6 }}

      jaeger_query:
        storage: {{ toYaml .Values.extensions.jaeger_query.storage | indent 8 }}
        ui: {{ toYaml .Values.extensions.jaeger_query.ui | indent 8 }}
      jaeger_storage: {{ toYaml .Values.extensions.jaeger_storage | indent 6 }}
      remote_sampling: {{ toYaml .Values.extensions.remote_sampling | indent 6 }}

    receivers:
      otlp: {{ toYaml .Values.receivers.otlp | indent 6 }}
      jaeger: {{ toYaml .Values.receivers.jaeger | indent 6 }}
      zipkin: {{ toYaml .Values.receivers.zipkin | indent 6 }}

    processors:
      batch: {{ toYaml .Values.processors.batch | indent 6 }}

    exporters:
      jaeger_storage_exporter: {{ toYaml .Values.exporters.jaeger_storage_exporter | indent 6 }}
