apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jaeger-v2.fullname" . }}
  namespace: {{ template "jaeger-v2.namespace" . }}
  labels:
        {{- include "jaeger-v2.labels" . | nindent 4 }}
data:
  config.yaml: |
        service:
          extensions:  [{{ join ", " .Values.service.extensions }}]
          pipelines:
            traces:
              receivers: [{{ join ", " .Values.service.pipelines.traces.receivers }}]
              processors: [{{ join ", " .Values.service.pipelines.traces.processors }}]
              exporters: [{{ join ", " .Values.service.pipelines.traces.exporters }}]

        extensions:
          {{- include "jaeger-v2.extensionsConfig" . | nindent 6 }}
        receivers:
          {{- include "jaeger-v2.receiversConfig" . | nindent 6 }}
        processors:
          {{- include "jaeger-v2.processorsConfig" . | nindent 6 }}
        exporters:
          {{- include "jaeger-v2.exportersConfig" . | nindent 6 }}
