apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jaeger-v2.fullname" . }}
  namespace: {{ template "jaeger-v2.namespace" . }}
  labels:
    {{- include "jaeger-v2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jaeger-v2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jaeger-v2.selectorLabels" . | nindent 8 }}
        {{- include "jaeger-v2.podLabels" . | nindent 8}}
    spec:
      containers:
        - name: jaeger-v2
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          args: 
            - "--config"
            - "/etc/jaeger/config.yaml"
          ports:
            - containerPort: 16686
              name: ui
            - containerPort: 14268
              name: collector
            - containerPort: 14250
              name: grpc
            - containerPort: 9411
              name: zipkin
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: jaeger-v2-config
              mountPath: /etc/jaeger
      volumes:
        - name: jaeger-v2-config
          configMap:
            name: {{ include "jaeger-v2.fullname" . }}